version: '3.8'
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ../../config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../../config/nginx/logs:/var/log/nginx

  nginx-prometheus-exporter:          # 노드 익스포터 같이 띄어줌 
    container_name: nginx-prometheus-exporter
    image: nginx/nginx-prometheus-exporter:latest
    ports:
      - "9113:9113"
    command: -nginx.scrape-uri http://nginx/metrics -web.telemetry-path=/metrics     
      #  익스포터가 스크립할때 http://nginx/metrics 가져온다  , -web.telemetry-path   ..외부로 노출할때는   /metrics  로 노출하겠다.
      # 엔진엑스는 기본적으로 /metrics 를 제공하고 있지 않음  따라서 config/nginx 에서 추가 설정 필요

  prometheus-nginxlog-exporter:
    container_name: prometheus-nginxlog-exporter
    image: quay.io/martinhelmich/prometheus-nginxlog-exporter
    ports:
      - "4040:4040"
    volumes:
      - ../../config/prometheus-nginxlog-exporter/prometheus-nginxlog-exporter.yml:/etc/prometheus-nginxlog-exporter.yml
      - ../../config/nginx/logs:/var/log/nginx
    command: '-config-file /etc/prometheus-nginxlog-exporter.yml'

networks:
  default:
    external:
      name: monitoring